name: arq_limpa
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"
#  flutter pub run build_runner build
dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  sqflite:
  path:
  cupertino_icons: ^1.0.2
  intl:
  mask_text_input_formatter:
  mockito: ^5.3.0
  build_runner: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true